-- Custom engines
ACF_DefineEngine("2.0-B4j", {
	name = "Toyota 4U-GSE",
	desc = "2.0L Toyota 4U-GSE B4 Engine.",
	model = "models/engines/b4med.mdl",
	sound = "acf_extra/vehiclefx/engines/fsp/b4_subaru_ej257.wav",
	category = "Custom-Flat",
	fuel = "Petrol",
	enginetype = "GenericPetrol",
	requiresfuel = false,
	weight = 80,
	torque = 245,
	flywheelmass = 0.3,
	idlerpm = 900,
	peakminrpm = 2500,
	peakmaxrpm = 7000,
	limitrpm = 7500,
})

ACF_DefineEngine("3.8-B6j", {
	name = "RUF CTR3 Engine",
	desc = "3.8L RUF CTR3 Flat-6 Engine.",
	model = "models/engines/b6med.mdl",
	sound = "acf_extra/vehiclefx/engines/fsp/b6_porsche_996.wav",
	category = "Custom-Flat",
	fuel = "Petrol",
	enginetype = "GenericPetrol",
	requiresfuel = false,
	weight = 130,
	torque = 850,
	flywheelmass = 0.3,
	idlerpm = 900,
	peakminrpm = 4000,
	peakmaxrpm = 7000,
	limitrpm = 7500,
})

ACF_DefineEngine("3.6-B6j", {
	name = "Porsche Engine",
	desc = "3.6L Porsche 964 RS Flat-6 Engine.",
	model = "models/engines/b6small.mdl",
	sound = "acf_extra/vehiclefx/engines/flat6/RSR_ONLOW2.WAV",
	category = "Custom-Flat",
	fuel = "Petrol",
	enginetype = "GenericPetrol",
	requiresfuel = false,
	weight = 130,
	torque = 412,
	flywheelmass = 0.3,
	idlerpm = 900,
	peakminrpm = 3000,
	peakmaxrpm = 6000,
	limitrpm = 6300,
})
