-- Custom engines
ACF_DefineEngine("GTD-1250", {
	name = "GTD-1250",
	desc = "T80U Turbine Engine",
	model = "models/engines/turbine_l.mdl",
	sound = "acf_engines/turbine_large.wav",
	category = "Custom-Turbine",
	fuel = "Multifuel",
	enginetype = "Turbine",
	requiresfuel = false,
	weight = 1050,
	torque = 3516,
	flywheelmass = 6,
	idlerpm = 2000,
	peakminrpm = 2350,
	peakmaxrpm = 6025,
	limitrpm = 8500,
	iselec = true,
	istrans = true,
	flywheeloverride = 4500,
})

ACF_DefineEngine("PD-12V", {
	name = "PD-12V",
	desc = "PD-12V TurboProp For Mil Mi-26",
	model = "models/engines/turbine_l.mdl",
	sound = "acf_engines/turbine_large.wav",
	category = "Custom-Turbine",
	fuel = "Multifuel",
	enginetype = "Turbine",
	requiresfuel = false,
	weight = 2660,
	torque = 16084.53,
	flywheelmass = 25,
	idlerpm = 2000,
	peakminrpm = 2350,
	peakmaxrpm = 6025,
	limitrpm = 8500,
	iselec = true,
	istrans = true,
	flywheeloverride = 8500,
})
