-- Custom engines
ACF_DefineEngine("AC-Induction-Motor", {
	name = "3-phase AC Induction Motor",
	desc = "Tesla P90D Electric motor!",
	model = "models/engines/emotor-standalone-sml.mdl",
	sound = "acf_engines/electric_small.wav",
	category = "Custom-Electric",
	fuel = "Electric",
	enginetype = "Electric",
	requiresfuel = false,
	weight = 20,
	torque = 500,
	flywheelmass = 0.1,
	idlerpm = 5,
	peakminrpm = 1,
	peakmaxrpm = 1,
	limitrpm = 10000,
	iselec = true,
	flywheeloverride = 5000,
})

ACF_DefineEngine("Electric-Funk", {
	name = "Why Not?",
	desc = "^ What else do you need?",
	model = "models/engines/emotor-standalone-sml.mdl",
	sound = "acf_engines/electric_small.wav",
	category = "Custom-Electric",
	fuel = "Electric",
	enginetype = "Electric",
	requiresfuel = false,
	weight = 5,
	torque = 5000,
	flywheelmass = 0.5,
	idlerpm = 5,
	peakminrpm = 1,
	peakmaxrpm = 1,
	limitrpm = 15000,
	iselec = true,
	flywheeloverride = 3000,
})
