-- Custom engines
ACF_DefineEngine("3.0-V6", {
	name = "Chrysler EcoDiesel",
	desc = "3.0L Chrysler EcoDiesel.",
	model = "models/engines/v6small.mdl",
	sound = "acf_engines/v6_diesellarge.wav",
	category = "Custom-V6",
	fuel = "Diesel",
	enginetype = "GenericDiesel",
	requiresfuel = false,
	weight = 325,
	torque = 569,
	flywheelmass = 1,
	idlerpm = 800,
	peakminrpm = 1000,
	peakmaxrpm = 3600,
	limitrpm = 4000,
})

ACF_DefineEngine("3.2-V6", {
	name = "Alfa Romeo Busso V6",
	desc = "3.2L Alfa Romeo Engine.",
	model = "models/engines/v6small.mdl",
	sound = "acf_extra/vehiclefx/engines/fsp/v6_honda_c32b.wav",
	category = "Custom-V6",
	fuel = "Petrol",
	enginetype = "GenericPetrol",
	requiresfuel = false,
	weight = 125,
	torque = 300,
	flywheelmass = 0.1,
	idlerpm = 800,
	peakminrpm = 3700,
	peakmaxrpm = 7000,
	limitrpm = 8000,
})

ACF_DefineEngine("3.7-V6", {
	name = "Nissan VQ37VHR",
	desc = "3.7L Nissan V6 Engine.",
	model = "models/engines/v6small.mdl",
	sound = "acf_extra/vehiclefx/engines/fsp/v6_nissan_vr38dett.wav",
	category = "Custom-V6",
	fuel = "Petrol",
	enginetype = "GenericPetrol",
	requiresfuel = false,
	weight = 142,
	torque = 365,
	flywheelmass = 0.15,
	idlerpm = 800,
	peakminrpm = 3500,
	peakmaxrpm = 6800,
	limitrpm = 7600,
})

ACF_DefineEngine("3.5-V6-4", {
	name = "Ford Raptor EcoBoost",
	desc = "3.5L EcoBoost V6 For The Raptor.",
	model = "models/engines/v6med.mdl",
	sound = "acf_engines/v6_diesellarge.wav",
	category = "Custom-V6",
	fuel = "Petrol",
	enginetype = "GenericPetrol",
	requiresfuel = false,
	weight = 250,
	torque = 558.5,
	flywheelmass = 0.45,
	idlerpm = 600,
	peakminrpm = 3500,
	peakmaxrpm = 4590,
	limitrpm = 6000,
})

ACF_DefineEngine("3.0-V6-2", {
	name = "Ford Vulcan V6",
	desc = "3.0L Ford Vulcan V6 Engine.",
	model = "models/engines/v6small.mdl",
	sound = "acf_extra/vehiclefx/engines/fsp/v6_ferrari_dino.wav",
	category = "Custom-V6",
	fuel = "Petrol",
	enginetype = "GenericPetrol",
	requiresfuel = false,
	weight = 126,
	torque = 257,
	flywheelmass = 0.15,
	idlerpm = 800,
	peakminrpm = 3500,
	peakmaxrpm = 5200,
	limitrpm = 6000,
})

ACF_DefineEngine("3.35-V6", {
	name = "GM LA1 V6",
	desc = "3.3L GM LA1 V6 Engine.",
	model = "models/engines/v6small.mdl",
	sound = "acf_extra/vehiclefx/engines/flat6/911S_onverylow.WAV",
	category = "Custom-V6",
	fuel = "Petrol",
	enginetype = "GenericPetrol",
	requiresfuel = false,
	weight = 150,
	torque = 280,
	flywheelmass = 0.15,
	idlerpm = 1000,
	peakminrpm = 2500,
	peakmaxrpm = 5200,
	limitrpm = 6000,
})

ACF_DefineEngine("3.7-V6D", {
	name = "Audi R18 E-Tron Quattro Engine",
	desc = "3.7L TurboDiesel, meant for speed.",
	model = "models/engines/v6small.mdl",
	sound = "acf_engines/v6_diesellarge.wav",
	category = "Custom-V6",
	fuel = "Diesel",
	enginetype = "GenericDiesel",
	requiresfuel = false,
	weight = 30,
	torque = 680,
	flywheelmass = 0.4,
	idlerpm = 900,
	peakminrpm = 1200,
	peakmaxrpm = 5500,
	limitrpm = 6000,
})
