-- Custom engines
ACF_DefineEngine("4.8-V10", {
	name = "Toyota 1LR-GUE V10",
	desc = "Lexus LFA Engine.",
	model = "models/engines/v10sml.mdl",
	sound = "acf_extra/vehiclefx/engines/fsp/v10_toyota_1lrgue.wav",
	category = "Custom-V10",
	fuel = "Petrol",
	enginetype = "GenericPetrol",
	weight = 236,
	torque = 400,
	requiresfuel = false,
	flywheelmass = 0.3,
	idlerpm = 900,
	peakminrpm = 4750,
	peakmaxrpm = 8700,
	limitrpm = 9500,
})

ACF_DefineEngine("250.0-V10", {
	name = "Heavy Ship Engine",
	desc = "250.0L Heavy Marine V10 Engine.",
	model = "models/engines/v10hvyb.mdl",
	sound = "acf_extra/vehiclefx/engines/gnomefather/meteor.wav",
	category = "Custom-V10",
	fuel = "Diesel",
	enginetype = "GenericDiesel",
	requiresfuel = false,
	weight = 20000,
	torque = 80000,
	flywheelmass = 10000,
	idlerpm = 50,
	peakminrpm = 50,
	peakmaxrpm = 500,
	limitrpm = 500,
})

ACF_DefineEngine("5.0-V10", {
	name = "BMW M5 V10 E60",
	desc = "5.0L BMW M5 V10 E60 V10 Engine.",
	model = "models/engines/v10med.mdl",
	sound = "acf_extra/vehiclefx/engines/v10/viper_on.wav",
	category = "Custom-V10",
	fuel = "Petrol",
	enginetype = "GenericPetrol",
	requiresfuel = false,
	weight = 255,
	torque = 416,
	flywheelmass = 0.2,
	idlerpm = 800,
	peakminrpm = 4000,
	peakmaxrpm = 7750,
	limitrpm = 8250,
})

ACF_DefineEngine("10ZG", {
	name = "Mitsubishi 10ZG 10-cylinder",
	desc = "Type 90 V10 TurboDiesel",
	model = "models/engines/v10big.mdl",
	sound = "acf_extra/vehiclefx/engines/panther.wav",
	category = "Custom-V10",
	fuel = "Diesel",
	enginetype = "GenericDiesel",
	requiresfuel = false,
	weight = 2000,
	torque = 3560.376,
	flywheelmass = 5,
	idlerpm = 300,
	peakminrpm = 500,
	peakmaxrpm = 2400,
	limitrpm = 3000,
})

ACF_DefineEngine("15.8-V10", {
	name = "Tatra 815 Engine",
	desc = "15.8L Tatra 815 Engine.",
	model = "models/engines/v10big.mdl",
	sound = "acf_extra/vehiclefx/engines/gnomefather/meteor.wav",
	category = "Custom-V10",
	fuel = "Diesel",
	enginetype = "GenericDiesel",
	requiresfuel = false,
	weight = 2000,
	torque = 2100,
	flywheelmass = 5,
	idlerpm = 300,
	peakminrpm = 500,
	peakmaxrpm = 1750,
	limitrpm = 1800,
})
