-- Custom engines
ACF_DefineEngine("2.4-V8", {
	name = "RS27-2013",
	desc = "2.4L F1 Engine for the  Lotus E21.",
	model = "models/engines/v8s.mdl",
	sound = "acf_extra/vehiclefx/engines/v8/38lv8_gp1_onhigh_in.wav",
	category = "Custom-V8",
	fuel = "Petrol",
	enginetype = "GenericPetrol",
	requiresfuel = false,
	weight = 95,
	torque = 250,
	flywheelmass = 0.3,
	idlerpm = 2000,
	peakminrpm = 5500,
	peakmaxrpm = 17000,
	limitrpm = 18000,
})

ACF_DefineEngine("5.8-V8", {
	name = "Nascar Stock Engine",
	desc = "5.8L V8 Nascar engine.",
	model = "models/engines/v8m.mdl",
	sound = "acf_extra/vehiclefx/engines/v8/clevv8_onlowex.wav",
	category = "Custom-V8",
	fuel = "Petrol",
	enginetype = "GenericPetrol",
	requiresfuel = false,
	weight = 260,
	torque = 705,
	flywheelmass = 0.4,
	idlerpm = 1000,
	peakminrpm = 4500,
	peakmaxrpm = 9000,
	limitrpm = 10000,
})

ACF_DefineEngine("8.2-V8", {
	name = "Top Fuel Engine",
	desc = "8.2L Top Fuel Dragster engine.",
	model = "models/engines/v8m.mdl",
	sound = "acf_engines/v8_special2.wav",
	category = "Custom-V8",
	fuel = "NitroMethane",
	enginetype = "GenericPetrol",
	requiresfuel = false,
	weight = 350,
	torque = 6500,
	flywheelmass = 8,
	idlerpm = 1000,
	peakminrpm = 3500,
	peakmaxrpm = 9000,
	limitrpm = 10000,
})

ACF_DefineEngine("3.9-V8", {
	name = "Ferrari F154",
	desc = "3.9L twin turbo.",
	model = "models/engines/v8s.mdl",
	sound = "acf_extra/vehiclefx/engines/v12/gtb4_onlow.wav",
	category = "Custom-V8",
	fuel = "Petrol",
	enginetype = "GenericPetrol",
	requiresfuel = false,
	weight = 110,
	torque = 760,
	flywheelmass = 0.3,
	idlerpm = 800,
	peakminrpm = 3000,
	peakmaxrpm = 8000,
	limitrpm = 10000,
})

ACF_DefineEngine("6.6-V8", {
	name = "AMC 401 V8",
	desc = "6.6L AMC 401 Cu In V8.",
	model = "models/engines/v8m.mdl",
	sound = "acf_extra/vehiclefx/engines/fsp/v8_gm_duramax_lly.wav",
	category = "Custom-V8",
	fuel = "Petrol",
	enginetype = "GenericPetrol",
	requiresfuel = false,
	weight = 350,
	torque = 433,
	flywheelmass = 0.25,
	idlerpm = 700,
	peakminrpm = 2500,
	peakmaxrpm = 4200,
	limitrpm = 6000,
})

ACF_DefineEngine("6.6-V8d2", {
	name = "6.6 L turbo DMAX Diesel V8",
	desc = "6.6 L turbo Duramax Diesel V8",
	model = "models/engines/v8m.mdl",
	sound = "acf_engines/v8_petrolmedium.wav",
	category = "Custom-V8",
	fuel = "Diesel",
	enginetype = "GenericDiesel",
	requiresfuel = false,
	weight = 450,
	torque = 564,
	flywheelmass = 1.5,
	idlerpm = 500,
	peakminrpm = 1800,
	peakmaxrpm = 3100,
	limitrpm = 4200,
})

ACF_DefineEngine("4.0-V8", {
	name = "Toyota 1UZ-FE V8",
	desc = "4.0L Toyota V8 Engine.",
	model = "models/engines/v8s.mdl",
	sound = "acf_extra/vehiclefx/engines/v8/bar_onverylow.wav",
	category = "Custom-V8",
	fuel = "Petrol",
	enginetype = "GenericPetrol",
	requiresfuel = false,
	weight = 165,
	torque = 420,
	flywheelmass = 0.2,
	idlerpm = 900,
	peakminrpm = 3200,
	peakmaxrpm = 6000,
	limitrpm = 7000,
})

ACF_DefineEngine("5.0-V8", {
	name = "Koenigsegg 5.0L TT-V8",
	desc = "5.0L Koenigsegg V8 Engine.",
	model = "models/engines/v8s.mdl",
	sound = "acf_extra/vehiclefx/engines/fsp/v8_oldsmobile_455.wav",
	category = "Custom-V8",
	fuel = "Petrol",
	enginetype = "GenericPetrol",
	requiresfuel = false,
	weight = 200,
	torque = 999,
	flywheelmass = 0.2,
	idlerpm = 1000,
	peakminrpm = 2700,
	peakmaxrpm = 7100,
	limitrpm = 7500,
})

ACF_DefineEngine("12.1-V8", {
	name = "Detroit Diesel 8V92",
	desc = "12.1L Detroit Diesel V8 Engine.",
	model = "models/engines/v8m.mdl",
	sound = "acf_extra/vehiclefx/engines/t62_2.wav",
	category = "Custom-V8",
	fuel = "Diesel",
	enginetype = "GenericDiesel",
	requiresfuel = false,
	weight = 1200,
	torque = 1690,
	flywheelmass = 2,
	idlerpm = 500,
	peakminrpm = 1000,
	peakmaxrpm = 2100,
	limitrpm = 2100,
})

ACF_DefineEngine("7.3-V8", {
	name = "Ford PowerStroke V8",
	desc = "7.3L Ford PowerStroke V8 Engine.",
	model = "models/engines/v8m.mdl",
	sound = "acf_extra/vehiclefx/engines/gnomefather/meteor.wav",
	category = "Custom-V8",
	fuel = "Diesel",
	enginetype = "GenericDiesel",
	requiresfuel = false,
	weight = 420,
	torque = 685,
	flywheelmass = 3,
	idlerpm = 800,
	peakminrpm = 1000,
	peakmaxrpm = 3000,
	limitrpm = 3500,
})

ACF_DefineEngine("7.4-V8", {
	name = "Chevrolet Big-Block V8 LS7",
	desc = "7.4L Chevrolet Big-Block V8 Engine.",
	model = "models/engines/v8m.mdl",
	sound = "acf_extra/vehiclefx/engines/v8/corvette69-onlow.wav",
	category = "Custom-V8",
	fuel = "Petrol",
	enginetype = "GenericPetrol",
	requiresfuel = false,
	weight = 250,
	torque = 830,
	flywheelmass = 0.3,
	idlerpm = 800,
	peakminrpm = 2800,
	peakmaxrpm = 5000,
	limitrpm = 5500,
})

ACF_DefineEngine("5.3-V8", {
	name = "GM 5.3 V8 EcoTec3 L83",
	desc = "5.3L GM Small-Block V8 Engine.",
	model = "models/engines/v8m.mdl",
	sound = "acf_extra/vehiclefx/engines/v8/corvette69-onlow.wav",
	category = "Custom-V8",
	fuel = "Petrol",
	enginetype = "GenericPetrol",
	requiresfuel = false,
	weight = 325,
	torque = 451.2,
	flywheelmass = 0.3,
	idlerpm = 800,
	peakminrpm = 2500,
	peakmaxrpm = 5500,
	limitrpm = 5800,
})

ACF_DefineEngine("6.3-V8", {
	name = "Mercedes-Benz M156 V8",
	desc = "Mercedes-Benz C63 AMG Black-Series V8 Engine.",
	model = "models/engines/v8m.mdl",
	sound = "acf_extra/vehiclefx/engines/v8/HTGTS_onlow.wav",
	category = "Custom-V8",
	fuel = "Petrol",
	enginetype = "GenericPetrol",
	requiresfuel = false,
	weight = 250,
	torque = 620,
	flywheelmass = 0.2,
	idlerpm = 900,
	peakminrpm = 3200,
	peakmaxrpm = 6800,
	limitrpm = 7000,
})

ACF_DefineEngine("6.2-V8", {
	name = "Dodge Challenger SRT Hellcat",
	desc = "Dodge Challenger SRT Hellcat Supercharged V8 Engine.",
	model = "models/engines/v8m.mdl",
	sound = "acf_extra/vehiclefx/engines/v8/corvette69-onlow.wav",
	category = "Custom-V8",
	fuel = "Petrol",
	enginetype = "GenericPetrol",
	requiresfuel = false,
	weight = 220,
	torque = 704,
	flywheelmass = 0.3,
	idlerpm = 850,
	peakminrpm = 2500,
	peakmaxrpm = 6000,
	limitrpm = 7000,
})

ACF_DefineEngine("4.6 SOHC V8", {
	name = "Ford Modular Engine",
	desc = "Ford Crown Victoria Police Interceptor.",
	model = "models/engines/v8m.mdl",
	sound = "acf_extra/vehiclefx/engines/v8/corvette69-onlow.wav",
	category = "Custom-V8",
	fuel = "Petrol",
	enginetype = "GenericPetrol",
	requiresfuel = false,
	weight = 120,
	torque = 322.4,
	flywheelmass = 0.2,
	idlerpm = 850,
	peakminrpm = 1500,
	peakmaxrpm = 5500,
	limitrpm = 6000,
})

ACF_DefineEngine("4.0-V8", {
	name = "BMW S65",
	desc = "4.0L petrol v8.",
	model = "models/engines/v8s.mdl",
	sound = "acf_extra/vehiclefx/engines/v12/gtb4_onlow.wav",
	category = "Custom-V8",
	fuel = "Petrol",
	enginetype = "GenericPetrol",
	requiresfuel = false,
	weight = 202,
	torque = 320,
	flywheelmass = 0.3,
	idlerpm = 800,
	peakminrpm = 3900,
	peakmaxrpm = 8300,
	limitrpm = 8400,
})
