-- Custom engines
ACF_DefineEngine("649CC-I2", {
	name = "649 cc I2",
	desc = "Kawasaki Ninja 650R engine, liquid-cooled 4 stroke parallel twin.",
	model = "models/engines/inline2s.mdl",
	sound = "acf_extra/vehiclefx/engines/l4/a110i2.wav",
	category = "Custom-Inline",
	fuel = "Petrol",
	enginetype = "GenericPetrol",
	requiresfuel = false,
	weight = 25,
	torque = 48.7,
	flywheelmass = 0.05,
	idlerpm = 800,
	peakminrpm = 3000,
	peakmaxrpm = 7200,
	limitrpm = 10000,
})

ACF_DefineEngine("471CC-whyunoshow-I2", {
	name = "471 cc I2",
	desc = "Honda CBR500R engine ohyea",
	model = "models/engines/inline2s.mdl",
	sound = "acf_extra/vehiclefx/engines/l4/Yugo_5_on.wav",
	category = "Custom-Inline",
	fuel = "Petrol",
	enginetype = "GenericPetrol",
	requiresfuel = false,
	weight = 45,
	torque = 42.4,
	flywheelmass = 0.015,
	idlerpm = 950,
	peakminrpm = 5500,
	peakmaxrpm = 6500,
	limitrpm = 8800,
})

ACF_DefineEngine("700cc-I2", {
	name = "700cc I2",
	desc = "Reliable little engine.",
	model = "models/engines/inline2s.mdl",
	sound = "acf_extra/vehiclefx/engines/warrior_2.wav",
	category = "Custom-Inline",
	fuel = "Petrol",
	enginetype = "GenericPetrol",
	requiresfuel = false,
	weight = 25,
	torque = 30,
	flywheelmass = 0.05,
	idlerpm = 750,
	peakminrpm = 2125,
	peakmaxrpm = 5400,
	limitrpm = 6000,
})

ACF_DefineEngine("2.4-I5", {
	name = "Volvo B5244S4",
	desc = "2.4L Volvo straight-5 with VVT",
	model = "models/engines/inline5s.mdl",
	sound = "acf_extra/vehiclefx/engines/l5/audis1_onmid.wav",
	category = "Custom-Inline",
	fuel = "Petrol",
	enginetype = "GenericPetrol",
	requiresfuel = false,
	weight = 125,
	torque = 230,
	flywheelmass = 0.15,
	idlerpm = 850,
	peakminrpm = 3000,
	peakmaxrpm = 6000,
	limitrpm = 8000,
})

ACF_DefineEngine("5.9-I6", {
	name = "Cummins B-Series",
	desc = "Large Diesel 4-cycle inline 6.",
	model = "models/engines/inline6m.mdl",
	sound = "acf_extra/vehiclefx/engines/t62.wav",
	category = "Custom-Inline",
	fuel = "Diesel",
	enginetype = "GenericDiesel",
	requiresfuel = false,
	weight = 535,
	torque = 596,
	flywheelmass = 1.6,
	idlerpm = 800,
	peakminrpm = 1200,
	peakmaxrpm = 2900,
	limitrpm = 3500,
})

ACF_DefineEngine("13.0-I6", {
	name = "Cummins X15 Performance Series",
	desc = "Large Diesel Cummins inline 6.",
	model = "models/engines/inline6l.mdl",
	sound = "acf_extra/vehiclefx/engines/scimitar.wav",
	category = "Custom-Inline",
	fuel = "Diesel",
	enginetype = "GenericDiesel",
	requiresfuel = false,
	weight = 1343,
	torque = 2779,
	flywheelmass = 3,
	idlerpm = 300,
	peakminrpm = 800,
	peakmaxrpm = 1900,
	limitrpm = 2000,
})

ACF_DefineEngine("International-I6", {
	name = "International A26",
	desc = "Large Diesel International inline 6.",
	model = "models/engines/inline6l.mdl",
	sound = "acf_extra/vehiclefx/engines/scimitar.wav",
	category = "Custom-Inline",
	fuel = "Diesel",
	enginetype = "GenericDiesel",
	requiresfuel = false,
	weight = 1043,
	torque = 1864,
	flywheelmass = 3,
	idlerpm = 300,
	peakminrpm = 600,
	peakmaxrpm = 1000,
	limitrpm = 2000,
})

ACF_DefineEngine("12.5-I6", {
	name = "Caterpillar C13",
	desc = "Large Diesel Caterpillar inline 6 for many construction vehicles.",
	model = "models/engines/inline6l.mdl",
	sound = "acf_extra/vehiclefx/engines/scimitar.wav",
	category = "Custom-Inline",
	fuel = "Diesel",
	enginetype = "GenericDiesel",
	requiresfuel = false,
	weight = 1143,
	torque = 2372,
	flywheelmass = 3,
	idlerpm = 300,
	peakminrpm = 500,
	peakmaxrpm = 2000,
	limitrpm = 2100,
})

ACF_DefineEngine("1.6-I4", {
	name = "Mazda B6 I4",
	desc = "1.6L Mazda B6 Inline-4 Engine.",
	model = "models/engines/inline4s.mdl",
	sound = "acf_extra/vehiclefx/engines/fsp/i6_bmw_s54b32.wav",
	category = "Custom-Inline",
	fuel = "Petrol",
	enginetype = "GenericPetrol",
	requiresfuel = false,
	weight = 142,
	torque = 365,
	flywheelmass = 0.15,
	idlerpm = 800,
	peakminrpm = 3500,
	peakmaxrpm = 6800,
	limitrpm = 7600,
})

ACF_DefineEngine("Z16XE", {
	name = "Opel Z16XE I4",
	desc = "1.6L Opel Z16XE Inline-4 Engine.",
	model = "models/engines/inline4s.mdl",
	sound = "acf_extra/vehiclefx/engines/fsp/i4_honda_b18c5.wav",
	category = "Custom-Inline",
	fuel = "Petrol",
	enginetype = "GenericPetrol",
	requiresfuel = false,
	weight = 120,
	torque = 150,
	flywheelmass = 0.15,
	idlerpm = 800,
	peakminrpm = 2500,
	peakmaxrpm = 5500,
	limitrpm = 7000,
})

ACF_DefineEngine("2.0-I4-1", {
	name = "Honda F20C I4",
	desc = "2.0L Honda F20C I4 Engine. Also... VTEC",
	model = "models/engines/inline4s.mdl",
	sound = "acf_extra/vehiclefx/engines/fsp/i4_honda_b18c5.wav",
	category = "Custom-Inline",
	fuel = "Petrol",
	enginetype = "GenericPetrol",
	requiresfuel = false,
	weight = 90,
	torque = 207,
	flywheelmass = 0.11,
	idlerpm = 870,
	peakminrpm = 6000,
	peakmaxrpm = 8600,
	limitrpm = 9000,
})

ACF_DefineEngine("2488-I4-B", {
	name = "Ford-Cosworth I4",
	desc = "Modified Ford Cosworth N/A Inline-4 for the BAC Mono",
	model = "models/engines/inline4s.mdl",
	sound = "acf_extra/vehiclefx/engines/fsp/i4_bmw_s14b23.wav",
	category = "Custom-Inline",
	fuel = "Petrol",
	enginetype = "GenericPetrol",
	requiresfuel = false,
	weight = 60,
	torque = 246.400,
	flywheelmass = 0.5,
	idlerpm = 800,
	peakminrpm = 4500,
	peakmaxrpm = 8000,
	limitrpm = 9500,
})

ACF_DefineEngine("2.4-I4-A", {
	name = "Nissan KA24DE I4",
	desc = "240SX yeeee",
	model = "models/engines/inline4s.mdl",
	sound = "acf_extra/vehiclefx/engines/fsp/i6_bmw_s54b32.wav",
	category = "Custom-Inline",
	fuel = "Petrol",
	enginetype = "GenericPetrol",
	requiresfuel = false,
	weight = 90,
	torque = 173.6,
	flywheelmass = 0.907,
	idlerpm = 920,
	peakminrpm = 2500,
	peakmaxrpm = 5600,
	limitrpm = 6250,
})

ACF_DefineEngine("2.0-I4-2", {
	name = "Toyota 3S-GE I4",
	desc = "2.0L Toyota 3S-GE I4 Engine.",
	model = "models/engines/inline4s.mdl",
	sound = "acf_extra/vehiclefx/engines/fsp/i4_bmw_s14b23.wav",
	category = "Custom-Inline",
	fuel = "Petrol",
	enginetype = "GenericPetrol",
	requiresfuel = false,
	weight = 90,
	torque = 191,
	flywheelmass = 0.1,
	idlerpm = 800,
	peakminrpm = 4000,
	peakmaxrpm = 7000,
	limitrpm = 8000,
})

ACF_DefineEngine("2.6-I6-1111", {
	name = "RB26DETT",
	desc = "2.6L Nissan Skyline GTR Engine, twin turbski",
	model = "models/engines/inline6m.mdl",
	sound = "acf_engines/l6_special.wav",
	category = "Custom-Inline",
	fuel = "Petrol",
	enginetype = "GenericPetrol",
	requiresfuel = false,
	weight = 160,
	torque = 313.6,
	flywheelmass = 0.3,
	idlerpm = 800,
	peakminrpm = 3800,
	peakmaxrpm = 6800,
	limitrpm = 8000,
})

ACF_DefineEngine("2.5-I6-2", {
	name = "Toyota 1JZ-GTE I6",
	desc = "2.5L Toyota 1JZ-GTE I6 Engine.",
	model = "models/engines/inline6s.mdl",
	sound = "acf_extra/vehiclefx/engines/fsp/i6_bmw_s54b32.wav",
	category = "Custom-Inline",
	fuel = "Petrol",
	enginetype = "GenericPetrol",
	requiresfuel = false,
	weight = 140,
	torque = 290.4,
	flywheelmass = 0.18,
	idlerpm = 800,
	peakminrpm = 3800,
	peakmaxrpm = 6200,
	limitrpm = 7000,
})

ACF_DefineEngine("3.0-I6-1", {
	name = "Toyota 2JZ-GE I6",
	desc = "3.0L Toyota 2JZ-GE I6 Engine.",
	model = "models/engines/inline6s.mdl",
	sound = "acf_extra/vehiclefx/engines/fsp/i6_bmw_s54b32.wav",
	category = "Custom-Inline",
	fuel = "Petrol",
	enginetype = "GenericPetrol",
	requiresfuel = false,
	weight = 120,
	torque = 280,
	flywheelmass = 0.125,
	idlerpm = 800,
	peakminrpm = 3800,
	peakmaxrpm = 6000,
	limitrpm = 6500,
})

ACF_DefineEngine("2.8-I6-B", {
	name = "BMW M52B28",
	desc = "oyus beamer engine",
	model = "models/engines/inline6s.mdl",
	sound = "acf_extra/vehiclefx/engines/l6/gavrilzetamed_acc.wav",
	category = "Custom-Inline",
	fuel = "Petrol",
	enginetype = "GenericPetrol",
	requiresfuel = false,
	weight = 125,
	torque = 224,
	flywheelmass = 0.3,
	idlerpm = 900,
	peakminrpm = 3950,
	peakmaxrpm = 5500,
	limitrpm = 6500,
})

ACF_DefineEngine("1.0-I3", {
	name = "Ford Fox I3",
	desc = "1.0L Ford Fox I3 Engine.",
	model = "models/engines/inline3s.mdl",
	sound = "acf_extra/vehiclefx/engines/l4/elite_onverylow.wav",
	category = "Custom-Inline",
	fuel = "Petrol",
	enginetype = "GenericPetrol",
	requiresfuel = false,
	weight = 60,
	torque = 200,
	flywheelmass = 0.1,
	idlerpm = 800,
	peakminrpm = 3500,
	peakmaxrpm = 6000,
	limitrpm = 7000,
})

ACF_DefineEngine("2.8-I4D", {
	name = "Duramax I4",
	desc = "2.8L Duramax I4 Engine.",
	model = "models/engines/inline4s.mdl",
	sound = "acf_engines/i4_dieselmedium.wav",
	category = "Custom-Inline",
	fuel = "Diesel",
	enginetype = "GenericDiesel",
	requiresfuel = false,
	weight = 100,
	torque = 500,
	flywheelmass = 2.5,
	idlerpm = 500,
	peakminrpm = 700,
	peakmaxrpm = 2000,
	limitrpm = 3500,
})

ACF_DefineEngine("3.9-I4D", {
	name = "4BT Cummins I4",
	desc = "3.9L 4BT Cummins I4 Engine.",
	model = "models/engines/inline4s.mdl",
	sound = "acf_engines/i4_diesellarge.wav",
	category = "Custom-Inline",
	fuel = "Diesel",
	enginetype = "GenericDiesel",
	requiresfuel = false,
	weight = 155,
	torque = 363,
	flywheelmass = 2,
	idlerpm = 500,
	peakminrpm = 600,
	peakmaxrpm = 1600,
	limitrpm = 2300,
})

ACF_DefineEngine("6.6-I6D", {
	name = "Cat C6.6 ACERT I6",
	desc = "6.6L Cat C6.6 ACERT I6 Engine.",
	model = "models/engines/inline6s.mdl",
	sound = "acf_engines/l6_dieselmedium.wav",
	category = "Custom-Inline",
	fuel = "Diesel",
	enginetype = "GenericDiesel",
	requiresfuel = false,
	weight = 155,
	torque = 363,
	flywheelmass = 2,
	idlerpm = 200,
	peakminrpm = 600,
	peakmaxrpm = 2000,
	limitrpm = 2200,
})

ACF_DefineEngine("110.8-I6D", {
	name = "Cat 3606 I6",
	desc = "110.8L Cat 3606 I6 Engine.",
	model = "models/engines/inline6l.mdl",
	sound = "acf_extra/vehiclefx/engines/gnomefather/maus.wav",
	category = "Custom-Inline",
	fuel = "Diesel",
	enginetype = "GenericDiesel",
	requiresfuel = false,
	weight = 6500,
	torque = 17000,
	flywheelmass = 100,
	idlerpm = 100,
	peakminrpm = 150,
	peakmaxrpm = 1000,
	limitrpm = 1000,
})
